import { ToolDefinition } from '../types';

/**
 * CentralAnswerTool - A simple Q&A tool for general questions
 * This tool is used when the agent needs to answer a question directly
 * without executing complex workflows.
 */
export class CentralAnswerTool implements ToolDefinition {
    name = 'central_answer';
    version = '1.0.0';
    description = 'Answer a general question or provide information directly to the user';
    tags = ['qa', 'general'];

    inputSchema = {
        type: 'object' as const,
        properties: {
            question: {
                type: 'string' as const,
                description: 'The question to answer'
            }
        },
        required: ['question']
    };

    outputSchema = {
        type: 'object' as const,
        properties: {
            question: { type: 'string' as const },
            note: { type: 'string' as const }
        }
    };

    // Legacy compatibility
    get parameters() {
        return this.inputSchema;
    }

    permissions = [];
    sideEffects = [];
    rateLimitPerMinute = 0;
    auditFields = [];
    mockSupported = false;

    async execute(input: { question: string }) {
        const { question } = input;

        // This is a placeholder - in reality, this would call the LLM
        // But since we're in the tool execution context, we just acknowledge
        // and let the runner handle the actual response generation

        return {
            ok: true,
            output: {
                question,
                note: 'Question received. Response will be generated by the main agent loop.'
            },
            logs: [`central_answer: Processing question: "${question.slice(0, 100)}..."`]
        };
    }
}
