import fs from 'fs';
import os from 'os';
import path from 'path';

jest.mock('../core/llm/intelligent-router', () => {
    const actual = jest.requireActual('../core/llm/intelligent-router');
    return {
        ...actual,
        routeToModel: jest.fn(async (messages: any[]) => {
            const prompt = String(messages?.[0]?.content || '');
            const id = (prompt.match(/id="([^"]+)"/) || [])[1] || 'probe-section';
            return `<section class="section" id="${id}"><h2>fresh-${id}</h2><p>generated by the consumer probe</p></section>`;
        }),
    };
});

jest.mock('../api/ws', () => ({
    broadcast: jest.fn(),
    broadcastThinkingDetail: jest.fn(),
    broadcastTerminalLine: jest.fn(),
}));

jest.mock('../core/quality/html-qa', () => ({
    reviewHtml: (html: string) => ({ html, issues: [], fixed: [] }),
    browserSmokeTest: jest.fn(async () => ({ skipped: true })),
    splitHtmlProject: () => ({ multiFile: false }),
    stripFabricatedScripts: (html: string) => ({ html, removed: [] }),
    dropDeadExternalScripts: jest.fn(async (html: string) => ({ html, removed: [] })),
}));

jest.mock('../core/quality/visual-audit', () => ({
    auditVisually: jest.fn(async () => ({ ran: true, score: 100, findings: [], metrics: {} })),
    visualRepairBrief: () => '',
}));

jest.mock('../core/quality/behaviour-audit', () => ({
    auditBehaviour: jest.fn(async () => ({ ran: true, score: 100, findings: [], controls: [], metrics: { dead: 0, pressed: 0, deadAnchors: 0 } })),
    behaviourRepairBrief: () => '',
}));

jest.mock('../core/quality/repair-engine', () => ({
    applyMechanicalRepairs: (html: string) => ({ html, applied: [], notesAr: [] }),
}));

jest.mock('../core/design/self-check', () => ({
    selfCheckScript: () => '',
}));

jest.mock('../modules/services/WorkspaceService', () => ({
    workspaceService: {
        getExplorerRoot: () => process.env.ARTIFACT_DIR,
    },
}));

jest.mock('../api/page-store', () => ({
    persistJoePages: jest.fn(() => ({ status: 'queued' })),
}));

jest.mock('../modules/tools/definitions/BrowserSmartTools', () => ({
    PANEL_BROWSER_SID: 'consumer-probe-browser',
}));

jest.mock('../modules/browser/manager', () => ({
    warmBrowserSession: jest.fn(),
}));

jest.mock('../modules/browser/wsHub', () => ({
    waitForPanelWatcher: jest.fn(async () => false),
}));

const artifactDir = fs.mkdtempSync(path.join(os.tmpdir(), 'joe-consumer-probe-'));
const previousArtifactDir = process.env.ARTIFACT_DIR;
process.env.ARTIFACT_DIR = artifactDir;

// Require after ARTIFACT_DIR is set: WebPageBuilderTool captures it at module load.
const { WebPageBuilderTool } = require('../modules/tools/definitions/WebPageBuilderTool') as typeof import('../modules/tools/definitions/WebPageBuilderTool');
const { checkpointKey } = require('../core/resume/checkpoint') as typeof import('../core/resume/checkpoint');
const { blueprintSections } = require('../core/design/blueprints') as typeof import('../core/design/blueprints');
const { planSections } = require('../core/design/section-writer') as typeof import('../core/design/section-writer');
const { routeToModel } = require('../core/llm/intelligent-router') as typeof import('../core/llm/intelligent-router');
const { broadcastThinkingDetail } = require('../api/ws') as typeof import('../api/ws');

const REQUEST = 'Build a landing page for Cedar Studio';
const KIND = 'landing';
const tool = new WebPageBuilderTool();

function checkpointFile(sessionId: string): string {
    const key = checkpointKey(sessionId, REQUEST, KIND);
    return path.join(artifactDir, '.checkpoints', `${key}.json`);
}

function seedValidEmptyCheckpoint(sessionId: string): void {
    const key = checkpointKey(sessionId, REQUEST, KIND);
    fs.mkdirSync(path.join(artifactDir, '.checkpoints'), { recursive: true });
    fs.writeFileSync(checkpointFile(sessionId), JSON.stringify({
        v: 1, key, requestPreview: REQUEST, ts: Date.now(), sections: {}, titles: {},
    }), 'utf8');
}

function seedValidCheckpoint(sessionId: string): void {
    const plans = planSections(blueprintSections(KIND));
    const first = plans[0];
    const key = checkpointKey(sessionId, REQUEST, KIND);
    fs.mkdirSync(path.join(artifactDir, '.checkpoints'), { recursive: true });
    fs.writeFileSync(checkpointFile(sessionId), JSON.stringify({
        v: 1, key, requestPreview: REQUEST, ts: Date.now(),
        sections: { [first.id]: `<section class="section" id="${first.id}"><h2>RESUMED-CONTENT</h2></section>` },
        titles: { [first.id]: 'resumed' },
    }), 'utf8');
}

async function runCase(name: string, sessionId: string, seed: 'missing' | 'empty' | 'corrupt' | 'valid'): Promise<void> {
    const file = checkpointFile(sessionId);
    fs.rmSync(path.dirname(file), { recursive: true, force: true });
    if (seed === 'corrupt') {
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, '{broken json', 'utf8');
    } else if (seed === 'empty') {
        seedValidEmptyCheckpoint(sessionId);
    } else if (seed === 'valid') {
        seedValidCheckpoint(sessionId);
    }
    (routeToModel as jest.Mock).mockClear();
    (broadcastThinkingDetail as jest.Mock).mockClear();
    const result = await tool.execute({ request: REQUEST }, { sessionId });
    const output = JSON.stringify(result?.output || {});
    const htmlFile = path.join(artifactDir, `joe-${sessionId}.html`);
    const html = fs.existsSync(htmlFile) ? fs.readFileSync(htmlFile, 'utf8') : '';
    const logs: string[] = Array.isArray(result?.logs) ? result.logs.map(String) : [];
    const thinking = (broadcastThinkingDetail as jest.Mock).mock.calls.map((c: any[]) => String(c[1] || c[0] || ''));
    const resumeMessages = thinking.filter((line: string) => /resum|استأنف|نقطة الحفظ/i.test(line));
    const resumedLogs = logs.filter(line => /resumed from checkpoint|من نقطة الحفظ/i.test(line));
    const freshMarkers = (html.match(/fresh-[a-z0-9-]+/g) || []).length;
    const resumedMarkers = (html.match(/RESUMED-CONTENT/g) || []).length;
    console.log(`CASE=${name}`);
    console.log(`SEEDED_STATE=${seed}`);
    console.log(`RESULT_OK=${result?.ok === true}`);
    console.log(`RESULT_ERROR=${String(result?.error || '')}`);
    console.log(`OUTPUT_MESSAGE=${String((result?.output as any)?.message || '')}`);
    console.log(`MODEL_SECTION_CALLS=${(routeToModel as jest.Mock).mock.calls.length}`);
    console.log(`RESUME_MESSAGE_COUNT=${resumeMessages.length}`);
    console.log(`RESUMED_SECTION_LOG_COUNT=${resumedLogs.length}`);
    console.log(`OUTPUT_FRESH_MARKERS=${freshMarkers}`);
    console.log(`OUTPUT_RESUMED_MARKERS=${resumedMarkers}`);
    console.log(`OUTPUT_BYTES=${Buffer.byteLength(output)}`);
    console.log(`HTML_BYTES=${Buffer.byteLength(html)}`);
    console.log(`FILE_EXISTS_AFTER=${fs.existsSync(file)}`);
    if (seed === 'corrupt') {
        expect(result?.ok).toBe(true);
        expect(resumeMessages.length).toBe(0);
        expect(resumedLogs.length).toBe(0);
        expect(freshMarkers).toBeGreaterThan(0);
        expect(resumedMarkers).toBe(0);
    }
    if (seed === 'empty' || seed === 'missing') {
        expect(result?.ok).toBe(true);
        expect(resumeMessages.length).toBe(0);
        expect(resumedLogs.length).toBe(0);
        expect(freshMarkers).toBeGreaterThan(0);
    }
    if (seed === 'valid') {
        expect(result?.ok).toBe(true);
        expect(resumeMessages.length).toBeGreaterThan(0);
        expect(resumedLogs.length).toBeGreaterThan(0);
        expect(resumedMarkers).toBeGreaterThan(0);
        expect(freshMarkers).toBeGreaterThan(0);
    }
}

describe('checkpoint consumer path', () => {
    afterAll(() => {
        if (previousArtifactDir === undefined) delete process.env.ARTIFACT_DIR;
        else process.env.ARTIFACT_DIR = previousArtifactDir;
        fs.rmSync(artifactDir, { recursive: true, force: true });
    });

    test('does not resume unreadable checkpoints and resumes only valid sections', async () => {
        await runCase('missing', 'consumer-probe-missing', 'missing');
        await runCase('empty', 'consumer-probe-empty', 'empty');
        await runCase('corrupt', 'consumer-probe-corrupt', 'corrupt');
        await runCase('valid_sections', 'consumer-probe-valid', 'valid');
    }, 120_000);
});
