
import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.join(__dirname, '../../.env') });

import { TaskExecutor } from '../agents/TaskExecutor';
import { TaskStep } from '../agents/TaskExecutor';
import fs from 'fs';

async function testNewBrain() {
    console.log('🧠 Testing Genesis "New Brain" Capabilities...\n');

    const rootDir = path.resolve(__dirname, '../../..');
    const testProjectDir = path.join(rootDir, 'temp_brain_test');

    // Cleanup previous run
    if (fs.existsSync(testProjectDir)) {
        fs.rmSync(testProjectDir, { recursive: true, force: true });
    }

    const executor = new TaskExecutor(rootDir);

    // Simulation of a High-Level Plan generated by GenesisAgent
    const plan: TaskStep[] = [
        {
            name: "1. Build Structure",
            tool: "scaffold_project",
            args: {
                baseDir: testProjectDir,
                structure: {
                    "src/main.py": "print('Hello World')",
                    "README.md": "# Test Project"
                }
            }
        },
        {
            name: "2. Injection of Code",
            tool: "file_write",
            args: {
                // Ensure absolute path
                path: path.join(testProjectDir, "src/secrets.py"),
                content: "API_KEY = 'sk-1234567890-HARDCODED-SECRET' # Vulnerability for scanner"
            }
        },
        {
            name: "3. Security Audit",
            tool: "security_scanner",
            args: {
                projectPath: testProjectDir,
                files: ["src/secrets.py"] // Relative path usually works as tool resolves it
            }
        },
        {
            name: "4. Version Control",
            tool: "git_ops",
            args: {
                operation: "init", // FIXED: action -> operation
                args: [testProjectDir] // git init <path>
            }
        }
    ];

    console.log(`🤖 Plan Loaded: ${plan.length} Steps.`);
    console.log(`   Target: ${testProjectDir}\n`);

    for (const step of plan) {
        console.log(`\n👉 Executing: ${step.name} [${step.tool}]`);
        try {
            const result = await executor.executeStep(step);
            if (result.success) {
                console.log(`   ✅ Success`);
                if (step.tool === 'security_scanner') {
                    const out = result.output as any;
                    console.log(`      [Scanner Output]: Found ${out.issues?.length || 0} issues (Expected > 0)`);
                }
                if (step.tool === 'git_ops') {
                    console.log(`      [Git Output]: ${JSON.stringify(result.output)}`);
                }
            } else {
                console.error(`   ❌ Failed: ${result.output}`);
            }
        } catch (e: any) {
            console.error(`   💥 CRITICAL ERROR: ${e.message}`);
        }
    }
}

testNewBrain();
