const { ProjectPlannerTool } = require('./src/modules/tools/definitions/ProjectPlannerTool');
const { executeTool } = require('./src/modules/services/ToolService');
const { WorkspaceService } = require('./src/modules/services/WorkspaceService');

async function runJoeDemo() {
    console.log("🚀 STARTING JOE FULL AUTONOMOUS DEMO...");
    
    const PlannerClass = ProjectPlannerTool.ProjectPlannerTool || ProjectPlannerTool;
    const planner = new PlannerClass();
    
    const prompt = "Create a simple calculator app with a README and index.js. Use a professional structure.";
    
    console.log(`\n📝 USER PROMPT: "${prompt}"`);
    const planResult = await planner.execute({ projectDescription: prompt });
    
    if (!planResult.ok) return;
    const plan = planResult.output;
    console.log(`✅ Project Planned: ${plan.projectName}`);
    
    const workspaceId = `victory-${Date.now()}`;
    const { workspaceService } = require('./src/modules/services/WorkspaceService');
    const workspaceRoot = workspaceService.getActiveRoot(workspaceId);
    console.log(`🔒 Secure Workspace: ${workspaceRoot}`);

    // Execute first 2 phases
    for (let i = 0; i < Math.min(2, plan.phases.length); i++) {
        const phase = plan.phases[i];
        console.log(`\n--- 🚀 PHASE ${phase.phaseNumber}: ${phase.name} ---`);
        
        for (const task of phase.tasks) {
            console.log(`\n🛠️  Executing: ${task.task}`);
            
            // Handle common tool name variations if any
            let toolName = task.tool;
            let args = task.args;

            // ELITE: Injecting a bit more intelligence to fix potential LLM hallucinations on the fly
            if (toolName === 'scaffold_project' && !args.structure) {
                console.log("   💡 Patching scaffold_project: Adding initial structure...");
                args.structure = {
                    "README.md": `# ${plan.projectName}\nGenerated by Joe Autonomous Agent.`,
                    "index.js": "// Entry point"
                };
            }

            const result = await executeTool(toolName, args, { 
                workspaceId,
                sessionId: 'victory-session'
            });
            
            if (result.ok) {
                console.log(`   ✅ Success!`);
            } else {
                console.error(`   ❌ Failed: ${result.error}`);
            }
        }
    }

    console.log("\n--- 🔍 VERIFYING ARTIFACTS ---");
    const { LsTool } = require('./src/modules/tools/definitions/SystemTools');
    const ls = new LsTool();
    const lsResult = await ls.execute({ path: '.' }, { workspaceId });
    
    if (lsResult.ok) {
        console.log("📂 Files Created:");
        lsResult.output.entries.forEach(e => console.log(`   📄 ${e}`));
    }

    console.log("\n✨ JOE VICTORY DEMO COMPLETED!");
}

runJoeDemo().catch(console.error);
